server:
  port: 8081

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8088
  application:
    name: user

management:
  endpoints:
    web:
      exposure:
        include: "*"

